export const BuildingDirectory = [
  {
    "Notre-Dame": {
      "Residence Halls": [
        {
          name: "Alumni Hall",
          latitude: 41.6984,
          longitude: -86.2339,
          id: "alumni-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Badin Hall",
          latitude: 41.7006,
          longitude: -86.2412,
          id: "badin-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Breen-Phillips Hall",
          latitude: 41.70278,
          longitude: -86.24,
          id: "breen-phillips-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Carroll Hall",
          latitude: 41.70194,
          longitude: -86.24778,
          id: "carroll-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Cavanaugh Hall",
          latitude: 41.702807,
          longitude: -86.237164,
          id: "cavanaugh-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Dillon Hall",
          latitude: 41.6984,
          longitude: -86.2339,
          id: "dillon-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Duncan Hall",
          latitude: 41.6984,
          longitude: -86.2339,
          id: "duncan-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Dunne Hall",
          latitude: 41.7045274,
          longitude: -86.2329434,
          id: "dunne-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Farley Hall",
          latitude: 41.7036468,
          longitude: -86.2361456,
          id: "farley-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Fisher Hall",
          latitude: 41.6984,
          longitude: -86.2339,
          id: "fisher-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Keenan Hall",
          latitude: 41.703917,
          longitude: -86.237477,
          id: "keenan-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Sacred Heart Parish Center",
          latitude: 41.7068221,
          longitude: -86.2450146,
          id: "sacred-heart-parish-center",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Baumer Hall",
          latitude: 41.697,
          longitude: -86.2414,
          id: "baumer-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Fischer Graduate Residences",
          latitude: 41.7051,
          longitude: -86.229,
          id: "fischer-graduate-residences",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Harper Hall",
          latitude: 41.69928,
          longitude: -86.238899,
          id: "harper-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Flaherty Hall",
          latitude: 41.7035,
          longitude: -86.2328,
          id: "flaherty-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
        {
          name: "Howard Hall",
          latitude: 41.700833,
          longitude: -86.241667,
          id: "howard-hall",
          type: "Residence Halls",
          location: "Notre Dame",
        },
      ],
      "Academic Buildings": [
        {
          name: "Law School",
          latitude: 41.698379,
          longitude: -86.23863,
          location: "Notre Dame",
          id: "law-school",
          buildingType: "Academic Buildings",
        },
        {
          name: "Hesburgh Library",
          latitude: 41.7023892,
          longitude: -86.2341526,
          id: "hesburgh-library",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Corbett Family Hall",
          latitude: 41.699192,
          longitude: -86.234851,
          id: "corbett-family-hall",
          location: "Notre Dame",
          buildingType: "Academic Buildings",
        },
        {
          name: "Walsh Family Hall of Architecture",
          latitude: 41.695,
          longitude: -86.235,
          id: "walsh-family-hall-of-architecture",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Jordan Hall of Science",
          latitude: 41.700685,
          longitude: -86.233075,
          id: "jordan-hall-of-science",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "DeBartolo Hall",
          latitude: 41.6982522,
          longitude: -86.2362484,
          id: "debartolo-hall",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Decio Faculty Hall",
          latitude: 41.700545,
          longitude: -86.235967,
          id: "decio-family-hall",
          location: "Notre Dame",
          buildingType: "Academic Buildings",
        },
        {
          name: "Stayer Center for Executive Education",
          latitude: 41.71048456,
          longitude: -86.2360535,
          id: "stayer-center-for-executive-education",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "O'Shaughnessy Hall",
          latitude: 41.7003185,
          longitude: -86.2356855,
          id: "oshaughnessy-hall",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Hayes-Healy Center",
          latitude: 41.700344,
          longitude: -86.236814,
          id: "hayes-healy-center",
          location: "Notre Dame",
          buildingType: "Academic Buildings",
        },
        {
          name: "Mendoza College of Business",
          latitude: 41.6970083,
          longitude: -86.2346583,
          id: "mendoza-college-of-business",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Raclin Murphy Museum of Art",
          latitude: 41.693889,
          longitude: -86.235,
          id: "raclin-murphy-museum-of-art",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Fitzpatrick College of Engineering",
          latitude: 41.699234,
          longitude: -86.23695,
          id: "fitzpatrick-college-of-engineering",
          location: "Notre Dame",
          buildingType: "Academic Buildings",
        },
        {
          name: "Riley Hall of Art & Design",
          latitude: 41.70083425,
          longitude: -86.23722792,
          id: "riley-hall-of-art-design",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Spes Unica Hall",
          latitude: 41.70632,
          longitude: -86.2570306,
          id: "spes-unica-hall",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "O'Neill Hall",
          latitude: 41.69822114,
          longitude: -86.2319385,
          id: "oneill-hall",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "DPAC",
          latitude: 41.694799,
          longitude: -86.236694,
          id: "DPAC",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
        {
          name: "Nieuwland Science Hall",
          latitude: 41.70153583,
          longitude: -86.2366288,
          id: "nieuwland-science-hall",
          type: "Academic Buildings",
          location: "Notre Dame",
        },
      ],
      "Student Buildings": [
        {
          name: "LaFortune Student Center",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "lafortune-student-center",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "LaFortune Food Court",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "lafortune-food-court",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Haggar Parlor",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "haggar-parlor",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Joyce Center",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "joyce-center",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Compton Family Ice Arena",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "compton-ice-arena",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Notre Dame Stadium",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "notre-dame-stadium",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Wellness Center",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "wellness-center",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Grotto of Our Lady of Lourdes",
          latitude: 41.7002,
          longitude: -86.2379,
          id: "grotto",
          type: "Student Buildings",
          location: "Notre Dame",
        },
        {
          name: "Basilica",
          latitude: 41.7026336,
          longitude: -86.2397856,
          id: "basilica-of-the-sacred-heart",
          type: "Student Buildings",
          location: "Notre Dame",
        },
      ],
    },
    "Holy-Cross": {
      "Academic Buildings": [
        {
          name: "Holy Cross College",
          latitude: 41.7000923,
          longitude: -86.2537078,
          location: "Holy Cross",
          buildingType: "Academic Buildings",
        },
      ],
    },
    "Saint-Marys": {},
  },
];

export const campuses = ["All", ...Object.keys(BuildingDirectory[0])];
export const locations = BuildingDirectory[0];
export const allBuildings = Object.values(BuildingDirectory[0])
  .flatMap((campus) => Object.values(campus))
  .flat();
